global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: kafka-exporter
    static_configs:
      - targets:
          - kafka-exporter:9308

  - job_name: telecom-consumer
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:18081
